### ISSUE TITLE
Rkt Panic

### ISSUE THREAD

**Issue by UserTaken** [skynetservices/skydns#201]
**How to Reproduce**:

`$ rkt --insecure-skip-verify run docker://skynetservices/skydns:latest -- -addr 0.0.0.0:53`

Another terminal:

`$ docker run --rm --dns 172.17.42.1 alpine ping docker.com`

Result everytime:

```
[ 1049.554860] skydns[5]: 2015/06/30 07:28:10 skydns: ready for queries on skydns.local. for tcp://0.0.0.0:53 [rcache 0]
[ 1049.555176] skydns[5]: 2015/06/30 07:28:10 skydns: ready for queries on skydns.local. for udp://0.0.0.0:53 [rcache 0]
[ 1054.909843] skydns[5]: panic: runtime error: invalid memory address or nil pointer dereference
[ 1054.910372] skydns[5]: [signal 0xb code=0x1 addr=0x0 pc=0x591b75]
[ 1054.910728] skydns[5]: goroutine 31 [running]:
[ 1054.911172] skydns[5]: github.com/skynetservices/skydns/server.(*server).ServeDNS(0xc208053000, 0x7f064a210ee8, 0xc208064ea0, 0xc2080627e0)
[ 1054.911546] skydns[5]: /home/miek/g/src/github.com/skynetservices/skydns/server/server.go:265 +0xb65
[ 1054.911919] skydns[5]: github.com/miekg/dns.(*ServeMux).ServeDNS(0xc208031480, 0x7f064a210ee8, 0xc208064ea0, 0xc2080627e0)
[ 1054.912306] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:182 +0xca
[ 1054.912765] skydns[5]: github.com/miekg/dns.(*Server).serve(0xc2081740e0, 0x7f064a210e10, 0xc208172300, 0x7f064a210d88, 0xc208031480, 0xc208078600, 0x1c, 0x200, 0xc208054158, 0xc20801d240, ...)
[ 1054.913056] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:479 +0x6c6
[ 1054.913389] skydns[5]: created by github.com/miekg/dns.(*Server).serveUDP
[ 1054.913650] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:437 +0x29a
[ 1054.914019] skydns[5]: goroutine 1 [semacquire]:
[ 1054.914349] skydns[5]: sync.(*WaitGroup).Wait(0xc20801cb80)
[ 1054.914659] skydns[5]: /home/miek/upstream/go/src/sync/waitgroup.go:132 +0x169
[ 1054.914957] skydns[5]: github.com/skynetservices/skydns/server.(*server).Run(0xc208053000, 0x0, 0x0)
[ 1054.915252] skydns[5]: /home/miek/g/src/github.com/skynetservices/skydns/server/server.go:158 +0x88e
[ 1054.915618] skydns[5]: main.main()
[ 1054.916154] skydns[5]: /home/miek/g/src/github.com/miekg/skydns/main.go:162 +0xa46
[ 1054.916514] skydns[5]: goroutine 7 [chan receive]:
[ 1054.917812] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.918274] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.918570] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.918879] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.919192] skydns[5]: goroutine 8 [chan receive]:
[ 1054.919476] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.919760] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.920105] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.920388] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.920675] skydns[5]: goroutine 9 [chan receive]:
[ 1054.920963] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.921258] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.921538] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.921817] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.922232] skydns[5]: goroutine 10 [chan receive]:
[ 1054.922550] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.922881] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.923137] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.923542] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.923909] skydns[5]: goroutine 11 [chan receive]:
[ 1054.924418] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.924761] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.925015] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.925259] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.925657] skydns[5]: goroutine 12 [chan receive]:
[ 1054.926210] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.926500] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.926735] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.926936] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.927145] skydns[5]: goroutine 13 [chan receive]:
[ 1054.927345] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.927521] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.927695] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.927972] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.928304] skydns[5]: goroutine 14 [chan receive]:
[ 1054.928521] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.928697] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.928871] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.929284] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.929460] skydns[5]: goroutine 15 [chan receive]:
[ 1054.929652] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.929851] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.930103] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.930302] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.930496] skydns[5]: goroutine 16 [chan receive]:
[ 1054.930677] skydns[5]: github.com/stathat/go.(*Reporter).processReports(0xc20801ca00)
[ 1054.930855] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:366 +0x58
[ 1054.931031] skydns[5]: created by github.com/stathat/go.NewReporter
[ 1054.931258] skydns[5]: /home/miek/g/src/github.com/stathat/go/stathat.go:93 +0x1a8
[ 1054.931812] skydns[5]: goroutine 29 [IO wait]:
[ 1054.931998] skydns[5]: net.(*pollDesc).Wait(0xc20800d640, 0x72, 0x0, 0x0)
[ 1054.932186] skydns[5]: /home/miek/upstream/go/src/net/fd_poll_runtime.go:84 +0x47
[ 1054.932362] skydns[5]: net.(*pollDesc).WaitRead(0xc20800d640, 0x0, 0x0)
[ 1054.932549] skydns[5]: /home/miek/upstream/go/src/net/fd_poll_runtime.go:89 +0x43
[ 1054.932728] skydns[5]: net.(*netFD).accept(0xc20800d5e0, 0x0, 0x7f064a20ec18, 0xc208031530)
[ 1054.933001] skydns[5]: /home/miek/upstream/go/src/net/fd_unix.go:419 +0x40b
[ 1054.933338] skydns[5]: net.(*TCPListener).AcceptTCP(0xc208054150, 0xacd368, 0x0, 0x0)
[ 1054.933641] skydns[5]: /home/miek/upstream/go/src/net/tcpsock_posix.go:234 +0x4e
[ 1054.934004] skydns[5]: github.com/miekg/dns.(*Server).serveTCP(0xc208174000, 0xc208054150, 0x0, 0x0)
[ 1054.934353] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:392 +0xfa
[ 1054.934766] skydns[5]: github.com/miekg/dns.(*Server).ListenAndServe(0xc208174000, 0x0, 0x0)
[ 1054.935025] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:268 +0x46c
[ 1054.935412] skydns[5]: github.com/miekg/dns.ListenAndServe(0x7ffc12fcbf4f, 0xa, 0x8acde0, 0x3, 0x7f064a210d88, 0xc208031480, 0x0, 0x0)
[ 1054.935672] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:95 +0xec
[ 1054.935937] skydns[5]: github.com/skynetservices/skydns/server.func·007()
[ 1054.936190] skydns[5]: /home/miek/g/src/github.com/skynetservices/skydns/server/server.go:143 +0xcd
[ 1054.936442] skydns[5]: created by github.com/skynetservices/skydns/server.(*server).Run
[ 1054.936733] skydns[5]: /home/miek/g/src/github.com/skynetservices/skydns/server/server.go:146 +0x9b3
[ 1054.937053] skydns[5]: goroutine 19 [IO wait]:
[ 1054.937479] skydns[5]: net.(*pollDesc).Wait(0xc20800ca00, 0x72, 0x0, 0x0)
[ 1054.937827] skydns[5]: /home/miek/upstream/go/src/net/fd_poll_runtime.go:84 +0x47
[ 1054.944211] skydns[5]: net.(*pollDesc).WaitRead(0xc20800ca00, 0x0, 0x0)
[ 1054.944434] skydns[5]: /home/miek/upstream/go/src/net/fd_poll_runtime.go:89 +0x43
[ 1054.944718] skydns[5]: net.(*netFD).Read(0xc20800c9a0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7f064a20ec18, 0xc2080311e0)
[ 1054.944951] skydns[5]: /home/miek/upstream/go/src/net/fd_unix.go:242 +0x40f
[ 1054.945206] skydns[5]: net.(*conn).Read(0xc208054090, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
[ 1054.945472] skydns[5]: /home/miek/upstream/go/src/net/net.go:121 +0xdc
[ 1054.945716] skydns[5]: net/http.noteEOFReader.Read(0x7f064a2107e0, 0xc208054090, 0xc2080583c8, 0xc20800f000, 0x1000, 0x1000, 0x7d3000, 0x0, 0x0)
[ 1054.945995] skydns[5]: /home/miek/upstream/go/src/net/http/transport.go:1270 +0x6e
[ 1054.946235] skydns[5]: net/http.(*noteEOFReader).Read(0xc20801c8a0, 0xc20800f000, 0x1000, 0x1000, 0xc208010000, 0x0, 0x0)
[ 1054.946490] skydns[5]: <autogenerated>:125 +0xd4
[ 1054.946851] skydns[5]: bufio.(*Reader).fill(0xc208064840)
[ 1054.947066] skydns[5]: /home/miek/upstream/go/src/bufio/bufio.go:97 +0x1ce
[ 1054.947324] skydns[5]: bufio.(*Reader).Peek(0xc208064840, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
[ 1054.947555] skydns[5]: /home/miek/upstream/go/src/bufio/bufio.go:132 +0xf0
[ 1054.947801] skydns[5]: net/http.(*persistConn).readLoop(0xc208058370)
[ 1054.948015] skydns[5]: /home/miek/upstream/go/src/net/http/transport.go:842 +0xa4
[ 1054.948266] skydns[5]: created by net/http.(*Transport).dialConn
[ 1054.948588] skydns[5]: /home/miek/upstream/go/src/net/http/transport.go:660 +0xc9f
[ 1054.948849] skydns[5]: goroutine 20 [select]:
[ 1054.949107] skydns[5]: net/http.(*persistConn).writeLoop(0xc208058370)
[ 1054.949381] skydns[5]: /home/miek/upstream/go/src/net/http/transport.go:945 +0x41d
[ 1054.950232] skydns[5]: created by net/http.(*Transport).dialConn
[ 1054.950540] skydns[5]: /home/miek/upstream/go/src/net/http/transport.go:661 +0xcbc
[ 1054.950804] skydns[5]: goroutine 30 [syscall]:
[ 1054.951064] skydns[5]: syscall.Syscall(0x2f, 0x6, 0xc20816f9f8, 0x0, 0x1c, 0x0, 0x0)
[ 1054.951521] skydns[5]: /home/miek/upstream/go/src/syscall/asm_linux_amd64.s:21 +0x5
[ 1054.951820] skydns[5]: syscall.recvmsg(0x6, 0xc20816f9f8, 0x0, 0x0, 0x0, 0x0)
[ 1054.952395] skydns[5]: /home/miek/upstream/go/src/syscall/zsyscall_linux_amd64.go:1933 +0x57
[ 1054.952697] skydns[5]: syscall.Recvmsg(0x6, 0xc208078a00, 0x200, 0x200, 0xc208172390, 0x28, 0x28, 0x0, 0x30, 0x0, ...)
[ 1054.952984] skydns[5]: /home/miek/upstream/go/src/syscall/syscall_linux.go:519 +0x19b
[ 1054.953290] skydns[5]: net.(*netFD).readMsg(0xc20800d650, 0xc208078a00, 0x200, 0x200, 0xc208172390, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
[ 1054.953435] skydns[5]: /home/miek/upstream/go/src/net/fd_unix.go:292 +0x42b
[ 1054.953583] skydns[5]: net.(*UDPConn).ReadMsgUDP(0xc208054158, 0xc208078a00, 0x200, 0x200, 0xc208172390, 0x28, 0x28, 0x67fb6d6, 0x7f064a1fd000, 0x40f891, ...)
[ 1054.953780] skydns[5]: /home/miek/upstream/go/src/net/udpsock_posix.go:96 +0x17f
[ 1054.953875] skydns[5]: github.com/miekg/dns.ReadFromSessionUDP(0xc208054158, 0xc208078a00, 0x200, 0x200, 0x200, 0x200, 0x0, 0x0)
[ 1054.953963] skydns[5]: /home/miek/g/src/github.com/miekg/dns/udp.go:44 +0xca
[ 1054.954103] skydns[5]: github.com/miekg/dns.(*Server).readUDP(0xc2081740e0, 0xc208054158, 0x77359400, 0x0, 0x0, 0x0, 0x1c, 0x0, 0x0)
[ 1054.954197] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:545 +0x14e
[ 1054.954281] skydns[5]: github.com/miekg/dns.(*Server).serveUDP(0xc2081740e0, 0xc208054158, 0x0, 0x0)
[ 1054.954378] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:427 +0x114
[ 1054.954490] skydns[5]: github.com/miekg/dns.(*Server).ListenAndServe(0xc2081740e0, 0x0, 0x0)
[ 1054.954629] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:282 +0x7c7
[ 1054.955657] skydns[5]: github.com/miekg/dns.ListenAndServe(0x7ffc12fcbf4f, 0xa, 0x8ad2e0, 0x3, 0x7f064a210d88, 0xc208031480, 0x0, 0x0)
[ 1054.956039] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:95 +0xec
[ 1054.956186] skydns[5]: github.com/skynetservices/skydns/server.func·008()
[ 1054.956326] skydns[5]: /home/miek/g/src/github.com/skynetservices/skydns/server/server.go:151 +0xcd
[ 1054.956463] skydns[5]: created by github.com/skynetservices/skydns/server.(*server).Run
[ 1054.956667] skydns[5]: /home/miek/g/src/github.com/skynetservices/skydns/server/server.go:154 +0xa98
[ 1054.956831] skydns[5]: goroutine 32 [runnable]:
[ 1054.956969] skydns[5]: github.com/miekg/dns.(*Server).serve(0xc2081740e0, 0x7f064a210e10, 0xc208172360, 0x7f064a210d88, 0xc208031480, 0xc208078800, 0x1c, 0x200, 0xc208054158, 0xc20801d260, ...)
[ 1054.957106] skydns[5]: /home/miek/g/src/github.com/miekg/dns/server.go:443
Sending SIGTERM to remaining processes...
Sending SIGKILL to remaining processes...
Halting system.
```

Tested with Rkt version 0.5.5 and 0.6.1. 

```
[root@localhost ~]# docker run -d --net host skynetservices/skydns:latest -addr 0.0.0.0:53
861b9ee3733b3b2b4e3fc6ea69287244b8db6ba759f6f1319818dd0e492e3fb7
[root@localhost ~]# docker run --rm --dns 172.17.42.1 alpine ping -c 3 docker.com
PING docker.com (162.242.195.82): 56 data bytes
64 bytes from 162.242.195.82: seq=0 ttl=61 time=87.723 ms
64 bytes from 162.242.195.82: seq=1 ttl=61 time=87.730 ms
64 bytes from 162.242.195.82: seq=2 ttl=61 time=87.564 ms

--- docker.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 87.564/87.672/87.730 ms
```

Works as expected.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[skydns] Rkt Panic (#201)..." ]
>**How to Reproduce**:
>
>`$ rkt --insecure-skip-verify run docker://skynetservices/skydns:latest -- -addr 0.0.0.0:53`
>
>Another terminal:
>
>`$ docker run --rm --dns 172.17.42.1 alpine ping docker.com`
>
>Result everytime:
>
>```
>[ 1049.554860] skydns[5]: 2015/06/30 07:28:10 skydns: ready for queries on skydns.local. for tcp://0.0.0.0:53 [rcache 0]
>[ 1049.555176] skydns[5]: 2015/06/30 07:28:10 skydns: ready for queries on skydns.local. for udp://0.0.0.0:53 [rcache 0]
>[ 1054.909843] skydns[5]: panic: runtime error: invalid memory address or nil pointer dereference
>[ 1054.910372] skydns[5]: [signal 0xb code=0x1 addr=0x0 pc=0x591b75]
>[ 1054.910728] skydns[5]: goroutine 31 [running]:
>[ 1054.911172] skydns[5]: github.com/skynetservices/skydns/server.(*server).ServeDNS(0xc208053000, 0x7f064a210ee8, 0xc208064ea0, 0xc2080627e0)
>[ 1054.911546] skydns[5]: /home/miek/g/src/github.com/skynetservices/skydns/server/server.go:265 +0xb65

Strange, the line it crashes on is:
```
      for zone, ns := range *s.config.stub {
```

Is this with -stubzones enabled?

**Comment by UserTaken** [comment]
@miekg Stub Zones are not enabled.

**Comment by miekg** [comment]
Ack.

Does rkt do socket activation or something?

**Comment by UserTaken** [comment]
@miekg The [metadata service](https://github.com/coreos/rkt/blob/master/Documentation/metadata-service.md) does but I am also not using that. Are you able to reproduce this?

**Comment by miekg** [comment]
I haven't setup rkt yet... Also wondering if I have the time to do this.

If you are able to debug some more that would greatly help.

**Comment by UserTaken** [comment]
Rkt is distro agnostic and 

```curl -L https://github.com/coreos/rkt/releases/download/v0.6.1/rkt-v0.6.1.tar.gz | tar xvzC /usr/local/bin --strip-components 1```

 is all that's needed for installation.

**Comment by miekg** [comment]
yes... But I won't have time to delve into this for at least a week...

**Comment by UserTaken** [comment]
@miekg That's fine; feel free to look into this whenever you have spare time.

**Comment by miekg** [comment]
So yes, confirmed. But rkt can't run local docker images?
