### ISSUE TITLE
Incomplete CNAME chain: rcode is not equal to success 

### ISSUE THREAD

**Issue by Dynom** [skynetservices/skydns#255]
Hi,

I'm using: Docker image `skynetservices/skydns:2.5.3a`

I sometimes get: 
```
SkyDNS:  2016/03/02 13:36:57 skydns: incomplete CNAME chain: rcode is not equal to success 
```

Always followed by some resolution failure:
```
2016-03-02T13:36:57.248Z - error: [Gatekeeper] getaddrinfo ENOTFOUND someservice.skydns.local someservice.skydns.local:3000 
      at errnoException (dns.js:26:10) 
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26) 
```

I can't reproduce it consistently, it happens at seemingly random intervals. hundreds of requests before went fine and hundreds after this message will go fine too.

Any suggestions as to what might be wrong?

**Comment by miekg** [comment]
Skydns tries to complete the entire chain and for that it will also
retrieve info from an upstream resolver. Does this chain point to a name
that is outside of the skydns domain? And what upstream is skydns using to
resolve this?

**Comment by Dynom** [comment]
I use SkyDNS to resolve locally available hosts only. It does, however, act as a conduit for hosts that aren't local.

SkyDNS is started like so:
```
ExecStart=/usr/bin/docker run \
  --name SkyDNS \
  --net=host \
  -e "SKYDNS_ADDR=${COREOS_PRIVATE_IPV4}:53" \
  -e "ETCD_MACHINES=http://${COREOS_PRIVATE_IPV4}:2379" \
  -e "SKYDNS_NAMESERVERS=8.8.8.8:53,8.8.4.4:53" \
  skynetservices/skydns:2.5.3a
```

**Comment by miekg** [comment]
Yeah so upstream is Google DNS. How many qps gets this service?

**Comment by Dynom** [comment]
virtually nothing, but even if I give it something to chew on it will succeed most of the time:
```
time sh -c 'for I in $(seq 1 1000); do ping -c1 user.skydns.local 2>/dev/null 1>/dev/null; echo -n $
?; done'
0000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
real	0m 27.67s
user	0m 0.02s
sys	0m 0.06s
```
So one failure in 1000 lookups in 27 seconds.

**Comment by miekg** [comment]
Interesting. Is it possible to capture a tcpdump from a trace like this?

**Comment by Dynom** [comment]
Just ran it for a while longer, have like 6 errors in almost 5 minutes (10.000 lookups) seems a bit slow to be honest. But that's besides the point (-:

**Comment by miekg** [comment]
There is no caching every query is going to etcd. But with catching one of
these failing queries it would be hard to debug this.

**Comment by Dynom** [comment]
```
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
15:02:12.389325 IP f94896b99c3e.58457 > 10.0.0.115.53: 3762+ A? user.skydns.local. (35)
15:02:12.389514 IP f94896b99c3e.58457 > 10.0.0.115.53: 4127+ AAAA? user.skydns.local. (35)
15:02:12.393207 IP f94896b99c3e.42100 > 10.0.0.115.53: 39562+ PTR? 115.0.0.10.in-addr.arpa. (41)
15:02:12.396774 IP 10.0.0.115.53 > f94896b99c3e.42100: 39562 NXDomain 0/0/0 (41)
15:02:12.417371 IP 10.0.0.115.53 > f94896b99c3e.58457: 4127* 1/0/0 CNAME internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. (117)
15:02:14.183124 IP 10.0.0.115.53 > f94896b99c3e.58457: 3762* 3/0/0 CNAME internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com., A 10.0.0.45, A 10.0.0.67 (149)
15:02:14.183408 IP f94896b99c3e > 10.0.0.45: ICMP echo request, id 29259, seq 0, length 64
15:02:14.183519 IP f94896b99c3e.37824 > 10.0.0.115.53: 64860+ PTR? 45.0.0.10.in-addr.arpa. (40)
15:02:14.183882 IP 10.0.0.45 > f94896b99c3e: ICMP echo reply, id 29259, seq 0, length 64
15:02:14.185863 IP 10.0.0.115.53 > f94896b99c3e.37824: 64860 NXDomain 0/0/0 (40)
15:02:15.183657 IP f94896b99c3e > 10.0.0.45: ICMP echo request, id 29259, seq 1, length 64
15:02:15.184134 IP 10.0.0.45 > f94896b99c3e: ICMP echo reply, id 29259, seq 1, length 64
15:02:15.185410 IP f94896b99c3e.37430 > 10.0.0.115.53: 43428+ A? user.skydns.local. (35)
15:02:15.185556 IP f94896b99c3e.37430 > 10.0.0.115.53: 43836+ AAAA? user.skydns.local. (35)
15:02:15.188341 IP 10.0.0.115.53 > f94896b99c3e.37430: 43836* 1/0/0 CNAME internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. (117)
15:02:15.246690 IP 10.0.0.115.53 > f94896b99c3e.37430: 43428* 0/1/0 (89)
15:02:15.253608 IP f94896b99c3e.56476 > 10.0.0.115.53: 23492+ A? user.skydns.local. (35)
15:02:15.254272 IP f94896b99c3e.56476 > 10.0.0.115.53: 23990+ AAAA? user.skydns.local. (35)
15:02:15.272834 IP 10.0.0.115.53 > f94896b99c3e.56476: 23990* 1/0/0 CNAME internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. (117)
15:02:15.281341 IP 10.0.0.115.53 > f94896b99c3e.56476: 23492* 3/0/0 CNAME internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com., A 10.0.0.45, A 10.0.0.67 (149)
15:02:15.281614 IP f94896b99c3e > 10.0.0.45: ICMP echo request, id 29771, seq 0, length 64
15:02:15.282083 IP 10.0.0.45 > f94896b99c3e: ICMP echo reply, id 29771, seq 0, length 64
15:02:17.892470 IP 10.0.0.61.51517 > f94896b99c3e.3000: Flags [S], seq 769528892, win 17922, options [mss 8961,sackOK,TS val 1193372553 ecr 0,nop,wscale 8], length 0
15:02:17.892508 IP f94896b99c3e.3000 > 10.0.0.61.51517: Flags [S.], seq 2849290700, ack 769528893, win 26847, options [mss 8961,sackOK,TS val 607857419 ecr 1193372553,nop,wscale 7], length 0
15:02:17.892476 IP 10.0.0.61.51499 > f94896b99c3e.3000: Flags [F.], seq 325635333, ack 616203192, win 71, options [nop,nop,TS val 1193372553 ecr 607797419], length 0
15:02:17.892663 IP f94896b99c3e.33264 > 10.0.0.115.53: 28322+ PTR? 61.0.0.10.in-addr.arpa. (40)
15:02:17.892840 IP f94896b99c3e.3000 > 10.0.0.61.51499: Flags [F.], seq 1, ack 1, win 210, options [nop,nop,TS val 607857419 ecr 1193372553], length 0
15:02:17.893032 IP 10.0.0.61.51517 > f94896b99c3e.3000: Flags [.], ack 1, win 71, options [nop,nop,TS val 1193372553 ecr 607857419], length 0
15:02:17.893389 IP 10.0.0.61.51499 > f94896b99c3e.3000: Flags [.], ack 2, win 71, options [nop,nop,TS val 1193372553 ecr 607857419], length 0
```

**Comment by Dynom** [comment]
Here the last one failed.
Command:
```
for I in $(seq 1 10000); do ping -c1 user.skydns.local 2>/dev/null 1>/dev/null; if [ $?
-ne 0 ]; then exit; fi; done`
```

Output:
```
15:13:15.000892 IP f94896b99c3e > 10.0.0.45: ICMP echo request, id 19838, seq 0, length 64
15:13:15.001435 IP 10.0.0.45 > f94896b99c3e: ICMP echo reply, id 19838, seq 0, length 64
15:13:15.002010 IP f94896b99c3e.33211 > 10.0.0.115.53: 23908+ A? user.skydns.local. (35)
15:13:15.002079 IP f94896b99c3e.33211 > 10.0.0.115.53: 24325+ AAAA? user.skydns.local. (35)
15:13:15.004441 IP 10.0.0.115.53 > f94896b99c3e.33211: 23908* 3/0/0 CNAME internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com., A 10.0.0.67, A 10.0.0.45 (149)
15:13:15.004672 IP 10.0.0.115.53 > f94896b99c3e.33211: 24325* 1/0/0 CNAME internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. (117)
```

Failing output, only has one CNAME it seems.
```
15:13:15.004869 IP f94896b99c3e > 10.0.0.67: ICMP echo request, id 20094, seq 0, length 64
15:13:15.005498 IP 10.0.0.67 > f94896b99c3e: ICMP echo reply, id 20094, seq 0, length 64
15:13:15.006102 IP f94896b99c3e.52411 > 10.0.0.115.53: 54446+ A? user.skydns.local. (35)
15:13:15.006157 IP f94896b99c3e.52411 > 10.0.0.115.53: 54879+ AAAA? user.skydns.local. (35)
15:13:15.028036 IP 10.0.0.115.53 > f94896b99c3e.52411: 54879* 1/0/0 CNAME internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. (117)
15:13:15.039209 IP 10.0.0.115.53 > f94896b99c3e.52411: 54446* 0/1/0 (89)
```

**Comment by Dynom** [comment]
Wait, `aaaa` is IPV6 right, can I force SkyDNS to reply to ipv4 only?

**Comment by miekg** [comment]
yep quad-a is v6, but skydns is not one doing it, the client asks for v6. This probably again ordering of the returning packet, hence the erratic nature of it. I should, really, really, really fix this real soon now.

**Comment by Dynom** [comment]
I've refactored part of my codebase to force ipv4 lookups only, I've tested it to see if that has any impact, since I don't use ipv6 internally anyway. Unfortunately it didn't have any effect it seems.

**Comment by Dynom** [comment]
Are you sure this has to do with ordering? It seems weird that there is one "empty" line, I wouldn't guess it has anything to do with ordering tbh.

**Comment by miekg** [comment]
Hmm, indeed.. So looking at the dumps, the non-working one does not have the IP addresses (which glibc expects)..
(doing some `dig`s), awesome response from amazon:
```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. IN A

;; ANSWER SECTION:
internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. 0	IN A 10.0.0.67
internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. 0	IN A 10.0.0.45

;; AUTHORITY SECTION:
eu-west-1.elb.amazonaws.com. 1414 IN	NS	ns-1053.awsdns-03.org.
eu-west-1.elb.amazonaws.com. 1414 IN	NS	ns-2023.awsdns-60.co.uk.
eu-west-1.elb.amazonaws.com. 1414 IN	NS	ns-341.awsdns-42.com.
eu-west-1.elb.amazonaws.com. 1414 IN	NS	ns-739.awsdns-28.net.
```
TTL of zero...

And here is your problem:
```
; <<>> DiG 9.10.3-P2-Ubuntu <<>> internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 8965
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;internal-Service-User-Staging-1506549669.eu-west-1.elb.amazonaws.com. IN A

;; Query time: 1386 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Mar 02 16:43:20 GMT 2016
;; MSG SIZE  rcvd: 97
```

**Comment by miekg** [comment]
In non technical term:s a fuck you from amazon via google

**Comment by miekg** [comment]
maybe amazon is rate limiting Google dns?

**Comment by miekg** [comment]
Each of the nameserver listed from amazon just works.

**Comment by miekg** [comment]
Other than "ratelimiting" I have no idea why this should happen... Maybe SkyDNS should retry on SERVFAIL in this case (don't think it does)

**Comment by Dynom** [comment]
Hm, not sure but maybe the hostname is shielded? It is an internal host.. shouldn't even be accessible from outside of the VPC I run it from.

**Comment by miekg** [comment]
What do you mean shielded? The name is in the public DNS, but that's the only I can find.

**Comment by Dynom** [comment]
Shielded I mean as in routing, firewalling, etc.

**Comment by miekg** [comment]
Ok, but for this issue that does not matter.

**Comment by miekg** [comment]
```
diff --git a/server/forwarding.go b/server/forwarding.go
index b0aaa45..f3656ae 100644
--- a/server/forwarding.go
+++ b/server/forwarding.go
@@ -111,7 +111,13 @@ func (s *server) Lookup(n string, t, bufsize uint16, dnssec bool) (*dns.Msg, err
 Redo:
        r, _, err := s.dnsUDPclient.Exchange(m, s.config.Nameservers[nsid])
        if err == nil {
-               if r.Rcode != dns.RcodeSuccess {
+               switch r.Rcode {
+               case dns.RcodeServerFailure:
+                       // On server failure try the next nameserver in the list.
+                       try++
+                       nsid = (nsid + 1) % len(s.config.Nameservers)
+                       goto Redo
+               default:
                        return nil, fmt.Errorf("rcode is not equal to success")
                }
                // Reset TTLs to rcache TTL to make some of the other code
```
Will probably help you in this case. Not that this tries the next upstream nameserver, so if you have only one this will not work. But you are using 2 (8.8 and 4.4).

**Comment by Dynom** [comment]
ah cool, is that part of a new release or for a local patch ?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [skydns] Incomplete CNAME chain..." ]
>ah cool, is that part of a new release or for a local patch ?

Local branch, but this will be added to SkyDNS shortly.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
https://github.com/skynetservices/skydns/pull/257

**Comment by Dynom** [comment]
Mind pushing it? Then I can create a build and test it on my test cluster

**Comment by Dynom** [comment]
We're actually migrating to Alpine Docker images, which would make this process even worse (since it'll query all ns in parallel and reply with the fastest one, see http://gliderlabs.viewdocs.io/docker-alpine/caveats/#dns).

Should specifying more DNS servers mitigate the problem? If so then I can add some more DNS servers.

**Comment by miekg** [comment]
alpine for skydns should not matter. You're talking about other apps running in containers on alpine?

Testing the branch would be appreciated :-)

**Comment by Dynom** [comment]
Hmm, you're right, that comment made no sense, since each container is registered with only 1 DNS server: SkyDNS. -_- Hey, it's early! ;-)

**Comment by miekg** [comment]
:-)

**Comment by Dynom** [comment]
Just for the record: Specifying more NS (6 total) to SkyDNS doesn't matter for this issue, although it does seem to perform a bit faster. But that's a very unscientific conclusion.

I'll try with your branch now.

**Comment by Dynom** [comment]
I've been testing it for quite a while, it seems to be fixed.

**Comment by miekg** [comment]
Good. I'll merge it later today.

**Comment by miekg** [comment]
ah, wait. Technically it can still happen, we just made the race condition smaller. Still Closing for now.
